# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-09-09 06:21
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle_models', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelstock',
            name='totalQty',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='vehiclemodels',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='vehiclename',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='importdetails',
            name='importDate',
            field=models.DateField(default='2017-09-09'),
        ),
        migrations.AlterField(
            model_name='model_stock',
            name='entry_date',
            field=models.DateField(default='2017-09-09'),
        ),
        migrations.AlterField(
            model_name='modelstock',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
